import { open, run, text } from "./drv.ts"
const { context, page } = await open()
await page.waitForTimeout(6000)
await run(page, `Run recall with the query "zarquon" and tell me exactly what it returned.`, 60000)
await page.waitForTimeout(15000)
const t = await text(page)
console.log("has code:", t.includes("zarquon-bcc8jy"))
const i = t.lastIndexOf("Run recall with the query")
console.log("AFTER-Q>>>", t.slice(i).replace(/\n+/g, " | ").slice(0, 1500))
await page.screenshot({ path: "/tmp/surfaces/10.8-recall2.png", fullPage: true })
await context.close()
