import { open, run, text } from "./drv.ts"
const { context, page, errors } = await open()
await page.waitForTimeout(4000)
const before = await text(page)
await run(page, "/reco.refresh", 10000)
const after = await text(page)
console.log("changed:", before !== after)
console.log("AFTER tail>>>", after.slice(-2500))
await page.screenshot({ path: "/tmp/surfaces/9.6.png" })
console.log("ERRORS", JSON.stringify(errors.slice(0, 5)))
await context.close()
