import { api, open, text } from "./drv.ts"
const { context, page } = await open({ reset: true })
await page.waitForTimeout(7000)
const fr = await api(page, "/api/reco/first-run")
const body = JSON.parse(fr.body)
console.log("first-run status", fr.status)
console.log("keys:", Object.keys(body))
console.log("needsSelection:", body.needsSelection, "degraded:", body.degraded, "emptySelection:", body.emptySelection)
console.log("recommendation:", JSON.stringify(body.recommendation)?.slice(0, 500))
console.log("digest repos:", JSON.stringify(body.digest?.repos ?? body.digest)?.slice(0, 400))
const w = await api(page, "/api/reco/watched")
console.log("watched:", w.body.slice(0, 300))
console.log("reco card count:", await page.locator(".reco-card").count())
await context.close()
