/**
 * Renders and installs the git hook scripts a WORKSPACE.ts declares.
 *
 * `S.Workspace(name, { gitHooks })` binds git hook events to ordinary
 * labeled targets. This module turns those bindings into
 * `.git/hooks/{pre-commit,post-commit,pre-push,post-merge}` scripts that
 * invoke the bound label through the `smthrs` CLI. Hook installation is
 * generated, drift-checked output exactly like CI generation: `check`
 * byte-compares, `install` publishes atomically, and nothing else writes
 * these files.
 *
 * A hook script fails open: when the `smthrs` binary is absent from PATH it
 * prints a warning and exits 0, because a missing build CLI must never block
 * a commit. The scripts are deterministic bytes, pinned by goldens.
 *
 * @since 0.1.0
 */
import * as Target from "@smthrs/targets/Target"
import type * as WorkspaceDeclaration from "@smthrs/targets/WorkspaceDeclaration"
import * as NodeCrypto from "node:crypto"
import * as Fs from "node:fs/promises"
import * as NodePath from "node:path"

/**
 * The refusal codes hook rendering and installation can fail with.
 *
 * @category models
 * @since 0.1.0
 */
export type ErrorCode =
  | "unlabeled_hook_target"
  | "invalid_label"
  | "not_a_git_repository"
  | "write_failed"

/**
 * One typed git-hooks refusal.
 *
 * @category errors
 * @since 0.1.0
 */
export class GitHooksError extends Error {
  override readonly name = "GitHooksError"
  readonly code: ErrorCode

  constructor(code: ErrorCode, message: string) {
    super(`${code}: ${message}`)
    this.code = code
  }
}

/**
 * Checks whether a value is a git-hooks refusal.
 *
 * @category guards
 * @since 0.1.0
 */
export const isGitHooksError = (value: unknown): value is GitHooksError => value instanceof GitHooksError

/**
 * The label lookup hook rendering needs from the package index.
 *
 * @category models
 * @since 0.1.0
 */
export interface LabelResolver {
  labelOf(target: Target.AnyTarget): string | undefined
}

/**
 * The workspace hook event names, in render order.
 *
 * @category constants
 * @since 0.1.0
 */
export const hookNames = ["preCommit", "postCommit", "prePush", "postMerge"] as const

/**
 * One workspace hook event name.
 *
 * @category models
 * @since 0.1.0
 */
export type HookName = (typeof hookNames)[number]

/**
 * The git hook file each workspace event installs to.
 *
 * @category constants
 * @since 0.1.0
 */
export const hookFiles: Readonly<Record<HookName, string>> = Object.freeze({
  preCommit: "pre-commit",
  postCommit: "post-commit",
  prePush: "pre-push",
  postMerge: "post-merge"
})

/** The exact label grammar a rendered script may carry: one shell word. */
const labelPattern = /^\/\/[A-Za-z0-9._/-]*:[A-Za-z0-9._-]+$/

/**
 * Resolves the workspace `gitHooks` bindings to labels through the index.
 *
 * Every bound hook target must be labeled: an unlisted target has no CLI
 * spelling for a script to invoke, so binding one is a graph error, not a
 * silently skipped hook.
 *
 * @category rendering
 * @since 0.1.0
 */
export const resolveHookLabels = (
  workspace: WorkspaceDeclaration.WorkspaceDeclaration,
  resolve: LabelResolver
): Readonly<Partial<Record<HookName, string>>> => {
  const bindings: Partial<Record<HookName, string>> = {}
  if (workspace.gitHooks === undefined) return bindings
  for (const hook of hookNames) {
    const target = workspace.gitHooks[hook]
    if (target === undefined) continue
    const label = resolve.labelOf(target)
    if (label === undefined) {
      throw new GitHooksError(
        "unlabeled_hook_target",
        `the ${hook} hook binds a target of rule ${
          Target.metadata(target).target
        } that no Package map lists; hooks need a label to invoke`
      )
    }
    bindings[hook] = label
  }
  return bindings
}

/** Renders one hook script for one bound label. */
const renderScript = (hookFile: string, label: string): string => {
  if (!labelPattern.test(label)) {
    throw new GitHooksError("invalid_label", `${JSON.stringify(label)} is not a renderable target label`)
  }
  return [
    "#!/bin/sh",
    "# Generated by smthrs from the WORKSPACE.ts gitHooks declaration. Do not edit.",
    `# ${hookFile} -> ${label}`,
    "if ! command -v smthrs >/dev/null 2>&1; then",
    `  echo "smthrs: CLI not found on PATH; skipping the ${hookFile} hook (fail-open)" >&2`,
    "  exit 0",
    "fi",
    `exec smthrs '${label}'`,
    ""
  ].join("\n")
}

/**
 * Renders the deterministic hook script set for resolved bindings.
 *
 * The result maps git hook file names (`pre-commit`, ...) to script bytes,
 * in the fixed {@link hookNames} order.
 *
 * @category rendering
 * @since 0.1.0
 */
export const render = (
  bindings: Readonly<Partial<Record<HookName, string>>>
): ReadonlyArray<{ readonly file: string; readonly content: string }> => {
  const rendered: Array<{ readonly file: string; readonly content: string }> = []
  for (const hook of hookNames) {
    const label = bindings[hook]
    if (label === undefined) continue
    rendered.push({ file: hookFiles[hook], content: renderScript(hookFiles[hook], label) })
  }
  return rendered
}

/**
 * One hook file's drift classification.
 *
 * @category models
 * @since 0.1.0
 */
export interface CheckEntry {
  readonly file: string
  readonly status: "clean" | "stale" | "missing"
}

/**
 * Byte-compares the rendered hook scripts against `.git/hooks` under `root`.
 *
 * @category checking
 * @since 0.1.0
 */
export const check = async (
  root: string,
  rendered: ReadonlyArray<{ readonly file: string; readonly content: string }>
): Promise<{ readonly clean: boolean; readonly entries: ReadonlyArray<CheckEntry> }> => {
  const hooksDirectory = NodePath.join(root, ".git", "hooks")
  const entries: Array<CheckEntry> = []
  for (const hook of rendered) {
    let status: CheckEntry["status"]
    try {
      const existing = await Fs.readFile(NodePath.join(hooksDirectory, hook.file), "utf8")
      status = existing === hook.content ? "clean" : "stale"
    } catch {
      status = "missing"
    }
    entries.push({ file: hook.file, status })
  }
  return { clean: entries.every((entry) => entry.status === "clean"), entries }
}

/**
 * Installs the rendered hook scripts into `.git/hooks` under `root`.
 *
 * Each script lands executable via a same-directory temporary name and
 * rename. A root that is not a git repository is a typed refusal.
 *
 * @category writing
 * @since 0.1.0
 */
export const install = async (
  root: string,
  rendered: ReadonlyArray<{ readonly file: string; readonly content: string }>
): Promise<{ readonly wrote: ReadonlyArray<string> }> => {
  const gitDirectory = NodePath.join(root, ".git")
  let stats
  try {
    stats = await Fs.stat(gitDirectory)
  } catch {
    throw new GitHooksError("not_a_git_repository", `${root} has no .git directory`)
  }
  if (!stats.isDirectory()) {
    throw new GitHooksError("not_a_git_repository", `${root} has no .git directory`)
  }
  const hooksDirectory = NodePath.join(gitDirectory, "hooks")
  const wrote: Array<string> = []
  for (const hook of rendered) {
    const absolute = NodePath.join(hooksDirectory, hook.file)
    const temporary = `${absolute}.tmp-${process.pid}-${NodeCrypto.randomBytes(4).toString("hex")}`
    try {
      await Fs.mkdir(hooksDirectory, { recursive: true })
      await Fs.writeFile(temporary, hook.content, { encoding: "utf8", mode: 0o755 })
      await Fs.rename(temporary, absolute)
    } catch (cause) {
      await Fs.rm(temporary, { force: true }).catch(() => undefined)
      throw new GitHooksError(
        "write_failed",
        `${hook.file} could not be installed: ${cause instanceof Error ? cause.message : String(cause)}`
      )
    }
    wrote.push(hook.file)
  }
  return { wrote }
}
