// Generated by @smthrs/create-app from the app directory. Do not edit.
// Regenerate with `pnpm routes`; `smthrs '//:routes'` checks for drift.
/* eslint-disable */

import * as pane_build_files from "./app/panes/build-files.tsx"
import * as pane_build_plan from "./app/panes/build-plan.tsx"
import * as pane_chain_balance from "./app/panes/chain-balance.tsx"
import * as pane_chain_block from "./app/panes/chain-block.tsx"
import * as pane_chain_contract from "./app/panes/chain-contract.tsx"
import * as pane_chain_tx from "./app/panes/chain-tx.tsx"
import * as layoutModule from "./app/layout.tsx"
import * as page__build from "./app/build/page.tsx"
import * as page__integrations from "./app/integrations/page.tsx"
import * as page__operate_deployments from "./app/operate/deployments/page.tsx"
import * as page__operate_logs from "./app/operate/logs/page.tsx"
import * as page__operate_observability from "./app/operate/observability/page.tsx"
import * as page__operate_transactions from "./app/operate/transactions/page.tsx"
import * as page__operate_usage from "./app/operate/usage/page.tsx"
import * as page__overview from "./app/overview/page.tsx"
import * as page__ from "./app/page.tsx"
import * as page__projects from "./app/projects/page.tsx"
import * as page__providers from "./app/providers/page.tsx"
import * as page__settings from "./app/settings/page.tsx"

export const layout = layoutModule.default

export const pages = [
  { route: "/build", file: "app/build/page.tsx", component: page__build.default },
  { route: "/integrations", file: "app/integrations/page.tsx", component: page__integrations.default },
  { route: "/operate/deployments", file: "app/operate/deployments/page.tsx", component: page__operate_deployments.default },
  { route: "/operate/logs", file: "app/operate/logs/page.tsx", component: page__operate_logs.default },
  { route: "/operate/observability", file: "app/operate/observability/page.tsx", component: page__operate_observability.default },
  { route: "/operate/transactions", file: "app/operate/transactions/page.tsx", component: page__operate_transactions.default },
  { route: "/operate/usage", file: "app/operate/usage/page.tsx", component: page__operate_usage.default },
  { route: "/overview", file: "app/overview/page.tsx", component: page__overview.default },
  { route: "/", file: "app/page.tsx", component: page__.default },
  { route: "/projects", file: "app/projects/page.tsx", component: page__projects.default },
  { route: "/providers", file: "app/providers/page.tsx", component: page__providers.default },
  { route: "/settings", file: "app/settings/page.tsx", component: page__settings.default },
] as const

export const panes = {
  "build-files": pane_build_files.Pane,
  "build-plan": pane_build_plan.Pane,
  "chain-balance": pane_chain_balance.Pane,
  "chain-block": pane_chain_block.Pane,
  "chain-contract": pane_chain_contract.Pane,
  "chain-tx": pane_chain_tx.Pane,
} as const
