// Generated by @smthrs/create-app from the flows and layer files. Do not edit.
// Regenerate with `pnpm routes`; `smthrs '//:routes'` checks for drift.
/* eslint-disable */

import * as layer0 from "./AGENT.ts"
import * as layer1 from "./SANDBOX.ts"
import * as layer2 from "./TOOLS.ts"
import * as layer3 from "./flows/build/AGENT.ts"
import * as flow_build from "./flows/build/flow.ts"
import * as flow_chat from "./flows/chat/flow.ts"

export const paneNames = ["build-files","build-plan","chain-balance","chain-block","chain-contract","chain-tx"] as const

export const flows = [
  { id: "build", file: "flows/build/flow.ts", spec: flow_build.Flow, agent: layer3.Agent, sandbox: layer1.Sandbox, tools: layer2.Tools },
  { id: "chat", file: "flows/chat/flow.ts", spec: flow_chat.Flow, agent: layer0.Agent, sandbox: layer1.Sandbox, tools: layer2.Tools },
] as const
