// Generated by @smthrs/create-app from the app directory. Do not edit.
// Regenerate with `pnpm routes`; `smthrs '//:routes'` checks for drift.
/* eslint-disable */

import * as pane_message from "./app/panes/message.tsx"
import * as layoutModule from "./app/layout.tsx"
import * as page__ from "./app/page.tsx"

export const layout = layoutModule.default

export const pages = [
  { route: "/", file: "app/page.tsx", component: page__.default },
] as const

export const panes = {
  "message": pane_message.Pane,
} as const
