// Generated by @smthrs/create-app from the flows and layer files. Do not edit.
// Regenerate with `pnpm routes`; `smthrs '//:routes'` checks for drift.
/* eslint-disable */

import * as layer0 from "./AGENT.ts"
import * as layer1 from "./SANDBOX.ts"
import * as layer2 from "./TOOLS.ts"
import * as flow_chat from "./flows/chat/flow.ts"

export const paneNames = ["message"] as const

export const flows = [
  { id: "chat", file: "flows/chat/flow.ts", spec: flow_chat.Flow, agent: layer0.Agent, sandbox: layer1.Sandbox, tools: layer2.Tools },
] as const
