/**
 * Generated compile-time file-path registries for `Smithers.file`.
 *
 * A registry is opt-in: only a workspace whose TypeScript program includes
 * the generated declaration narrows `Smithers.file`. Discovery delegates to
 * {@link Input.discoverFiles}, keeping its ignore, confinement, state-path,
 * and resource-limit rules as the single workspace scan implementation.
 *
 * @since 0.1.0
 */
import * as Effect from "effect/Effect"
import * as NodePath from "node:path"
import * as GeneratedFile from "./GeneratedFile.ts"
import * as Input from "./Input.ts"

/**
 * Default generated declaration path.
 *
 * @category constants
 * @since 0.1.0
 */
export const defaultOutput = "known-files.d.ts"

/**
 * The deterministic result of a known-file workspace scan.
 *
 * @category models
 * @since 0.1.0
 */
export interface Discovery {
  readonly files: ReadonlyArray<string>
  readonly packageDirectories: ReadonlyArray<string>
  readonly literals: ReadonlyArray<string>
}

/** Reports whether a workspace file is a BUILD.ts or PACKAGE.ts marker. */
const isPackageMarker = (path: string): boolean =>
  path === "BUILD.ts" || path === "PACKAGE.ts" || path.endsWith("/BUILD.ts") || path.endsWith("/PACKAGE.ts")

/** Returns the normalized directory holding a package marker. */
const markerDirectory = (path: string): string => {
  const directory = NodePath.posix.dirname(path)
  return directory === "." ? "" : directory
}

const localTo = (directory: string, path: string): string => directory === "" ? path : path.slice(directory.length + 1)

/**
 * Computes accepted literals from an already-discovered workspace file list.
 *
 * Two spellings are accepted, because those are the two a declaration
 * writes: the workspace-absolute `//path` of every file, and the
 * package-local `path` of every file below a directory holding a `BUILD.ts`
 * or `PACKAGE.ts`. `..` spellings are not emitted; a declaration that reaches
 * outside its package says so with `//`.
 *
 * @category generation
 * @since 0.1.0
 */
export const knownFileDiscovery = (
  discovered: ReadonlyArray<string>,
  options: {
    readonly output?: string | undefined
  } = {}
): Discovery => {
  const files = [...new Set([...discovered, GeneratedFile.resolveOutputPath(options.output ?? defaultOutput)])].sort()
  const packageDirectories = [...new Set(files.filter(isPackageMarker).map(markerDirectory))].sort()
  const literals = new Set(files.map((path) => `//${path}`))
  for (const directory of packageDirectories) {
    for (const path of files) {
      if (directory === "" || path.startsWith(`${directory}/`)) literals.add(localTo(directory, path))
    }
  }
  return {
    files,
    packageDirectories,
    literals: [...literals].sort()
  }
}

/**
 * Scans a workspace with the declared-input walk and computes its registry.
 *
 * @category generation
 * @since 0.1.0
 */
export const discoverKnownFiles = async (
  workspaceRoot: string,
  options: {
    readonly output?: string | undefined
    readonly cacheDirectory?: string | undefined
    readonly limits?: Partial<Input.ScanLimits> | undefined
    readonly signal?: AbortSignal | undefined
  } = {}
): Promise<Discovery> =>
  knownFileDiscovery(
    await Input.discoverFiles(workspaceRoot, {
      ...(options.cacheDirectory === undefined ? {} : { cacheDirectory: options.cacheDirectory }),
      ...(options.limits === undefined ? {} : { limits: options.limits }),
      ...(options.signal === undefined ? {} : { signal: options.signal })
    }),
    options
  )

/**
 * Renders ambient declarations consumed by plain `tsc`.
 *
 * @category generation
 * @since 0.1.0
 */
export const renderKnownFileDeclaration = (discovery: Discovery): string => {
  return `// Generated by @smthrs/targets KnownFile. Do not edit.\n` +
    `// The ${discovery.files.length} workspace files below follow the same .gitignore and host-state rules as globs.\n` +
    `// // entries are workspace-absolute; bare entries are relative to a directory holding a BUILD.ts or PACKAGE.ts.\n` +
    `declare module "@smthrs/targets/KnownFiles" {\n` +
    `  export type KnownFile =\n` +
    discovery.literals.map((path) => `      | ${JSON.stringify(path)}\n`).join("") +
    `}\n\n` +
    `declare module "@smthrs/targets" {\n` +
    `  export const Smithers: Omit<typeof import("@smthrs/targets/Smithers"), "file"> & {\n` +
    `    readonly file: (path: import("@smthrs/targets/KnownFiles").KnownFile) => ` +
    `import("@smthrs/targets/Input").File\n` +
    `  }\n` +
    `}\n`
}

const payload = async (
  workspaceRoot: string,
  output: string,
  signal?: AbortSignal | undefined
): Promise<GeneratedFile.FilePayload> => ({
  path: output,
  contents: renderKnownFileDeclaration(await discoverKnownFiles(workspaceRoot, { output, signal }))
})

/**
 * Scans and atomically writes one known-file declaration.
 *
 * @category effects
 * @since 0.1.0
 */
export const writeKnownFileDeclaration = (
  workspaceRoot: string,
  output = defaultOutput
): Effect.Effect<void, GeneratedFile.WriteFileError | CauseError> =>
  Effect.flatMap(
    Effect.tryPromise({
      try: (signal) => payload(workspaceRoot, output, signal),
      catch: causeError
    }),
    (generated) => GeneratedFile.writeGeneratedFile(workspaceRoot, generated)
  )

/**
 * Scans and checks one known-file declaration for drift.
 *
 * @category effects
 * @since 0.1.0
 */
export const checkKnownFileDeclaration = (
  workspaceRoot: string,
  output = defaultOutput
): Effect.Effect<void, GeneratedFile.DriftError | CauseError> =>
  Effect.flatMap(
    Effect.tryPromise({
      try: (signal) => payload(workspaceRoot, output, signal),
      catch: causeError
    }),
    (generated) => GeneratedFile.checkGeneratedFile(workspaceRoot, generated)
  )

/**
 * A workspace scan could not produce a known-file declaration.
 *
 * @category errors
 * @since 0.1.0
 */
export class CauseError extends Error {
  readonly _tag = "smithers-build/KnownFileError"
}

const causeError = (cause: unknown): CauseError =>
  new CauseError(`could not generate known-file declaration: ${GeneratedFile.failureMessage(cause)}`, { cause })
